platform :ios, '10.0'
use_frameworks!

target 'Briize' do

pod 'SideMenu'
pod 'RAMPaperSwitch', '~> 2.0.4'
pod 'NVActivityIndicatorView'
pod 'Parse'
pod 'Bolts-Swift'

  target 'BriizeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
