platform :ios, '10.0'
use_frameworks!

target 'Briize' do

pod 'SideMenu'
pod 'NVActivityIndicatorView'
pod 'Parse'
pod 'Bolts-Swift'
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'Mapbox-iOS-SDK', '~> 3.7'

  target 'BriizeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
